odoo:
  extends:
    file: common.yml
    service: odoo
  volumes:
    - ./modules:/mnt/extra-addons/
  links:
    - database:db
  container_name: odoo_docker_tmp

database:
  extends:
    file: common.yml
    service: database
  container_name: postgres_docker_tmp
  ports:
    - "5432:5432"
